using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Azure.AI.OpenAI;
using Azure.Identity;
using LambdaRag.Core;
using LambdaRag.Core.Domain;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Configuration;

namespace LambdaRag.Tools.LlmGroundTruth;

/// <summary>
/// LLM-judged ground truth generator for the cross-industry harness.
///
/// Walks tests/Goldens/corpus/{vertical}/{doc-id}/, and for every
/// (ruleset, document) pair where expected-llm.json is missing or stale
/// (different ruleset_fingerprint / document_hash), asks the configured
/// chat model whether the document satisfies each rule. The verdict —
/// one of PASS / FAIL / NOT_APPLICABLE — is written to
/// expected-llm.json keyed by rule id.
///
/// This file IS THE GROUND TRUTH the AccuracyHarness compares the
/// engine against. It is generated by humans (running this tool), then
/// committed and frozen. Re-generation only happens when the ruleset or
/// the source document changes — fingerprint drift on either input
/// invalidates the cached judgement and the tool re-asks the LLM.
///
/// Usage:
///   dotnet run --project tools/LlmGroundTruth
///     [--corpus &lt;path&gt;]      # default: tests/Goldens/corpus
///     [--vertical &lt;name&gt;]    # restrict to one vertical
///     [--doc &lt;id&gt;]            # restrict to one doc (requires --vertical)
///     [--force]                # ignore cache and re-ask the LLM
///     [--dry-run]              # show what would happen, no LLM calls
/// </summary>
internal static class Program
{
    private const string UserSecretsId = "lambda-rag-cli-3f1e7b8c-9c2a-4f6e-bf2a-2c5b9c6d4e10";

    public static async Task<int> Main(string[] args)
    {
        var flags = ParseFlags(args);
        var corpusRoot = flags.GetValueOrDefault("--corpus")
                         ?? DefaultCorpusRoot();
        var verticalFilter = flags.GetValueOrDefault("--vertical");
        var docFilter = flags.GetValueOrDefault("--doc");
        var force = flags.ContainsKey("--force");
        var dryRun = flags.ContainsKey("--dry-run");

        if (!Directory.Exists(corpusRoot))
        {
            Console.Error.WriteLine($"corpus root not found: {corpusRoot}");
            return 64;
        }

        var configuration = new ConfigurationBuilder()
            .AddUserSecrets(UserSecretsId)
            .AddEnvironmentVariables()
            .Build();

        IChatClient? chat = dryRun ? null : BuildChatClient(configuration);
        if (!dryRun && chat is null)
        {
            Console.Error.WriteLine(
                "LambdaRag:Foundry:Edit:Endpoint and :Deployment must be configured " +
                "(see ComplianceEditorFactory for the convention).");
            return 64;
        }

        var scenarios = EnumerateScenarios(corpusRoot, verticalFilter, docFilter).ToList();
        Console.WriteLine($"Found {scenarios.Count} scenario(s) under {corpusRoot}");

        var generated = 0;
        var skipped = 0;
        var failed = 0;

        foreach (var sc in scenarios)
        {
            Console.WriteLine($"\n── {sc.Vertical}/{sc.DocId} ──────────────────────────────");

            var ruleset = LoadRuleSet(sc.RulesetPath);
            var sourceText = await File.ReadAllTextAsync(sc.SourcePath);
            var rulesetFingerprint = ComputeRuleSetFingerprint(ruleset);
            var documentHash = ComputeDocumentHash(sourceText);

            var cached = TryReadExisting(sc.ExpectedLlmPath);
            if (!force
                && cached is not null
                && cached.RulesetFingerprint == rulesetFingerprint
                && cached.DocumentHash == documentHash
                && AllRuleIdsCovered(cached, ruleset))
            {
                Console.WriteLine($"  ✓ up-to-date ({cached.PerRule.Count} verdicts cached)");
                skipped++;
                continue;
            }

            if (dryRun)
            {
                Console.WriteLine($"  [dry-run] would judge {ruleset.Rules.Count} rule(s)");
                continue;
            }

            try
            {
                var verdicts = await JudgeAsync(chat!, ruleset, sourceText, sc);
                var output = new ExpectedLlm
                {
                    SchemaVersion = "1.0.0",
                    GeneratedAt = DateTimeOffset.UtcNow,
                    Model = ChatModelHint(configuration),
                    RulesetId = ruleset.Id,
                    RulesetVersion = ruleset.Version,
                    RulesetFingerprint = rulesetFingerprint,
                    DocumentHash = documentHash,
                    DocumentPath = $"{sc.Vertical}/{sc.DocId}/source.md",
                    PerRule = verdicts,
                };
                WriteExpected(sc.ExpectedLlmPath, output);
                Console.WriteLine($"  ✓ wrote {sc.ExpectedLlmPath} ({verdicts.Count} verdicts)");
                generated++;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"  ✗ failed: {ex.Message}");
                failed++;
            }
        }

        Console.WriteLine($"\nDone. generated={generated} skipped(cached)={skipped} failed={failed}");
        return failed == 0 ? 0 : 1;
    }

    // ── scenario discovery ─────────────────────────────────────────────

    private sealed record Scenario(
        string Vertical,
        string DocId,
        string RulesetPath,
        string SourcePath,
        string ExpectedLlmPath);

    private static IEnumerable<Scenario> EnumerateScenarios(
        string corpusRoot, string? verticalFilter, string? docFilter)
    {
        foreach (var verticalDir in Directory.EnumerateDirectories(corpusRoot)
                     .OrderBy(p => p, StringComparer.Ordinal))
        {
            var vertical = Path.GetFileName(verticalDir);
            if (verticalFilter is not null && !string.Equals(vertical, verticalFilter, StringComparison.Ordinal))
                continue;
            var rulesetPath = Path.Combine(verticalDir, "ruleset.json");
            if (!File.Exists(rulesetPath)) continue;

            foreach (var docDir in Directory.EnumerateDirectories(verticalDir)
                         .OrderBy(p => p, StringComparer.Ordinal))
            {
                var docId = Path.GetFileName(docDir);
                if (docFilter is not null && !string.Equals(docId, docFilter, StringComparison.Ordinal))
                    continue;
                var sourcePath = Path.Combine(docDir, "source.md");
                if (!File.Exists(sourcePath)) continue;
                yield return new Scenario(
                    vertical,
                    docId,
                    rulesetPath,
                    sourcePath,
                    Path.Combine(docDir, "expected-llm.json"));
            }
        }
    }

    // ── LLM call ───────────────────────────────────────────────────────

    private static async Task<Dictionary<string, RuleVerdict>> JudgeAsync(
        IChatClient chat, RuleSet ruleset, string sourceText, Scenario scenario)
    {
        // We judge ONE rule at a time. Cost is modest (5–15 rules per doc,
        // ~12 docs) and per-rule prompting gives us clean rationales we can
        // commit alongside the verdict for human audit. Batching all rules
        // in one prompt introduced cross-rule contamination in pilot runs.
        var verdicts = new Dictionary<string, RuleVerdict>(StringComparer.Ordinal);
        foreach (var rule in ruleset.Rules)
        {
            var systemPrompt =
                "You are a strict policy auditor. Given a single rule and a candidate document, " +
                "decide whether the document SATISFIES the rule. " +
                "Reply with PASS, FAIL, or NOT_APPLICABLE only. " +
                "PASS = the document clearly meets the rule's requirement. " +
                "FAIL = the document is subject to the rule but does not meet it (or contradicts it). " +
                "NOT_APPLICABLE = the rule does not apply to this kind of document. " +
                "Quote the SHORTEST verbatim span from the document that drove your decision " +
                "(or write \"(no relevant span)\" if NOT_APPLICABLE). " +
                "Return JSON ONLY with this exact shape: " +
                "{\"verdict\":\"PASS|FAIL|NOT_APPLICABLE\",\"evidence\":\"<verbatim span>\",\"reason\":\"<one sentence>\"}";

            var userPrompt = new StringBuilder();
            userPrompt.AppendLine($"RULE ID: {rule.Id}");
            userPrompt.AppendLine($"RULE: {rule.NaturalLanguage}");
            // NOTE: evidenceQuote is intentionally NOT included. It tends
            // to widen the LLM's interpretation past what the rule's
            // naturalLanguage actually requires (the auditor reads the
            // evidence as additional requirements rather than background
            // citation). The rule's naturalLanguage is the contract; we
            // judge strictly against that.
            userPrompt.AppendLine();
            userPrompt.AppendLine("DOCUMENT:");
            userPrompt.AppendLine(Truncate(sourceText, 12000));

            var response = await chat.GetResponseAsync(
                new[]
                {
                    new ChatMessage(ChatRole.System, systemPrompt),
                    new ChatMessage(ChatRole.User, userPrompt.ToString()),
                }).ConfigureAwait(false);

            var parsed = ParseVerdict(response.Text);
            verdicts[rule.Id] = parsed;
            Console.WriteLine($"    {rule.Id,-32} {parsed.Verdict,-15} {Shorten(parsed.Reason, 80)}");
        }
        return verdicts;
    }

    private static RuleVerdict ParseVerdict(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return new RuleVerdict { Verdict = "FAIL", Evidence = "", Reason = "(empty LLM response)" };

        // Be tolerant of code-fenced or prefixed responses.
        var trimmed = raw.Trim();
        var firstBrace = trimmed.IndexOf('{');
        var lastBrace = trimmed.LastIndexOf('}');
        if (firstBrace < 0 || lastBrace <= firstBrace)
            return new RuleVerdict { Verdict = "FAIL", Evidence = "", Reason = $"(unparseable: {Shorten(trimmed, 60)})" };

        var json = trimmed.Substring(firstBrace, lastBrace - firstBrace + 1);
        try
        {
            var node = JsonNode.Parse(json) as JsonObject
                       ?? throw new FormatException("not a JSON object");
            var verdict = (node["verdict"]?.GetValue<string>() ?? "FAIL").Trim().ToUpperInvariant();
            if (verdict is not ("PASS" or "FAIL" or "NOT_APPLICABLE"))
                verdict = "FAIL";
            return new RuleVerdict
            {
                Verdict = verdict,
                Evidence = node["evidence"]?.GetValue<string>() ?? "",
                Reason = node["reason"]?.GetValue<string>() ?? "",
            };
        }
        catch (Exception ex)
        {
            return new RuleVerdict
            {
                Verdict = "FAIL",
                Evidence = "",
                Reason = $"(parse error: {ex.Message})",
            };
        }
    }

    // ── persistence ────────────────────────────────────────────────────

    public sealed class ExpectedLlm
    {
        public string SchemaVersion { get; init; } = "1.0.0";
        public DateTimeOffset GeneratedAt { get; init; }
        public string Model { get; init; } = "";
        public string RulesetId { get; init; } = "";
        public string RulesetVersion { get; init; } = "";
        public string RulesetFingerprint { get; init; } = "";
        public string DocumentHash { get; init; } = "";
        public string DocumentPath { get; init; } = "";
        public Dictionary<string, RuleVerdict> PerRule { get; init; } = new();
    }

    public sealed class RuleVerdict
    {
        public string Verdict { get; init; } = "FAIL";
        public string Evidence { get; init; } = "";
        public string Reason { get; init; } = "";
    }

    private static readonly JsonSerializerOptions WriteOpts = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
    };

    private static ExpectedLlm? TryReadExisting(string path)
    {
        if (!File.Exists(path)) return null;
        try
        {
            return JsonSerializer.Deserialize<ExpectedLlm>(
                File.ReadAllText(path),
                new JsonSerializerOptions
                {
                    PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
                    PropertyNameCaseInsensitive = true,
                });
        }
        catch
        {
            return null;
        }
    }

    private static void WriteExpected(string path, ExpectedLlm value)
    {
        // Sort per_rule by key for stable diffs.
        var sorted = new Dictionary<string, RuleVerdict>(
            value.PerRule.OrderBy(kv => kv.Key, StringComparer.Ordinal),
            StringComparer.Ordinal);
        var toWrite = new ExpectedLlm
        {
            SchemaVersion = value.SchemaVersion,
            GeneratedAt = value.GeneratedAt,
            Model = value.Model,
            RulesetId = value.RulesetId,
            RulesetVersion = value.RulesetVersion,
            RulesetFingerprint = value.RulesetFingerprint,
            DocumentHash = value.DocumentHash,
            DocumentPath = value.DocumentPath,
            PerRule = sorted,
        };
        File.WriteAllText(path, JsonSerializer.Serialize(toWrite, WriteOpts));
    }

    private static bool AllRuleIdsCovered(ExpectedLlm cached, RuleSet ruleset)
        => ruleset.Rules.All(r => cached.PerRule.ContainsKey(r.Id));

    // ── fingerprints ───────────────────────────────────────────────────

    private static string ComputeRuleSetFingerprint(RuleSet ruleset)
    {
        // Fingerprint over the data the LLM actually saw: rule ids,
        // naturalLanguage, evidenceQuote, severity, applicability. Predicate
        // / lambda are irrelevant to the LLM's verdict — they're how the
        // engine answers, not what the truth is.
        var sb = new StringBuilder();
        foreach (var r in ruleset.Rules.OrderBy(r => r.Id, StringComparer.Ordinal))
        {
            sb.Append(r.Id).Append('|')
                  .Append(r.NaturalLanguage).Append('|')
                  .Append(r.Severity).Append('|')
                  .Append(r.Applicability).Append('\n');
        }
        return "lr1:" + Sha256(sb.ToString());
    }

    private static string ComputeDocumentHash(string sourceText)
        => "lr1:" + Sha256(sourceText);

    private static string Sha256(string input)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(input));
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }

    // ── chat client ────────────────────────────────────────────────────

    private static IChatClient? BuildChatClient(IConfiguration configuration)
    {
        // Mirror ComplianceEditorFactory's convention: Edit:Endpoint +
        // Edit:Deployment, Entra ID by default, API key when supplied.
        var endpoint = configuration["LambdaRag:Foundry:Edit:Endpoint"]
                       ?? Environment.GetEnvironmentVariable("LAMBDA_RAG_FOUNDRY_EDIT_ENDPOINT")
                       ?? configuration["LambdaRag:Foundry:Embed:Endpoint"]
                       ?? Environment.GetEnvironmentVariable("LAMBDA_RAG_FOUNDRY_ENDPOINT");
        var deployment = configuration["LambdaRag:Foundry:Edit:Deployment"]
                         ?? Environment.GetEnvironmentVariable("LAMBDA_RAG_FOUNDRY_EDIT_DEPLOYMENT");
        if (string.IsNullOrWhiteSpace(endpoint) || string.IsNullOrWhiteSpace(deployment))
            return null;

        var apiKey = configuration["LambdaRag:Foundry:Edit:ApiKey"]
                     ?? Environment.GetEnvironmentVariable("LAMBDA_RAG_FOUNDRY_EDIT_API_KEY");
        var azure = string.IsNullOrWhiteSpace(apiKey)
            ? new AzureOpenAIClient(new Uri(endpoint), new DefaultAzureCredential())
            : new AzureOpenAIClient(new Uri(endpoint), new Azure.AzureKeyCredential(apiKey));
        return azure.GetChatClient(deployment).AsIChatClient();
    }

    private static string ChatModelHint(IConfiguration configuration)
        => configuration["LambdaRag:Foundry:Edit:Deployment"]
           ?? Environment.GetEnvironmentVariable("LAMBDA_RAG_FOUNDRY_EDIT_DEPLOYMENT")
           ?? "unknown";

    // ── ruleset load ───────────────────────────────────────────────────

    private static RuleSet LoadRuleSet(string path)
    {
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<RuleSet>(json, CanonicalJson.Options)
               ?? throw new InvalidDataException($"empty ruleset: {path}");
    }

    // ── misc ───────────────────────────────────────────────────────────

    private static string Truncate(string s, int max)
        => s.Length <= max ? s : s.Substring(0, max) + "\n…[truncated]";

    private static string Shorten(string s, int max)
        => string.IsNullOrEmpty(s) ? "" : (s.Length <= max ? s : s.Substring(0, max - 1) + "…");

    private static string DefaultCorpusRoot()
    {
        // Project file lives at repo/tools/LlmGroundTruth/. AppContext.BaseDirectory
        // is bin/Debug/net9.0/. Walk up to the repo root.
        var here = AppContext.BaseDirectory;
        return Path.GetFullPath(Path.Combine(here, "..", "..", "..", "..", "..", "tests", "Goldens", "corpus"));
    }

    private static Dictionary<string, string> ParseFlags(string[] args)
    {
        var flags = new Dictionary<string, string>(StringComparer.Ordinal);
        for (var i = 0; i < args.Length; i++)
        {
            var a = args[i];
            if (!a.StartsWith("--", StringComparison.Ordinal)) continue;
            var hasValue = i + 1 < args.Length && !args[i + 1].StartsWith("--", StringComparison.Ordinal);
            flags[a] = hasValue ? args[++i] : "true";
        }
        return flags;
    }
}
