<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LambdaRag.Core\LambdaRag.Core.csproj" />
    <ProjectReference Include="..\LambdaRag.Persistence\LambdaRag.Persistence.csproj" />
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="TopicMaps\*.json" />
    <EmbeddedResource Include="data\*.txt" />
  </ItemGroup>
</Project>
