using System.Text.Json;
using Azure.AI.OpenAI;
using Azure.Identity;
using LambdaRag.Authoring.Synopsis;
using LambdaRag.Core;
using LambdaRag.Core.Domain;
using Microsoft.Extensions.AI;

namespace LambdaRag.Cli;

/// <summary>
/// `lambda-rag rules synopsize` — authoring-time tool that walks a ruleset
/// and writes a one-sentence plain-English synopsis into each rule's
/// <c>Metadata["synopsis"]</c> field. Synopses are generated by a small
/// chat model (gpt-4o-mini at the configured Azure OpenAI endpoint) and
/// disk-cached by content hash so repeated runs are free.
///
/// Runtime is unaffected: the markup pipeline reads the cached string at
/// review time without any LLM call. Determinism is preserved.
///
/// Required environment variables (or override via flags):
///   AZURE_OPENAI_ENDPOINT          e.g. https://my-foundry.cognitiveservices.azure.com/
///   AZURE_OPENAI_MINI_DEPLOYMENT   e.g. gpt-4o-mini
///
/// Auth uses <see cref="DefaultAzureCredential"/> (Entra ID) — no keys.
/// </summary>
internal static class SynopsizeCommand
{
    public static async Task<int> RunAsync(string[] args)
    {
        var f = ParseFlags(args);
        var rulesetPath = f.GetValueOrDefault("ruleset")
            ?? throw new ArgumentException("--ruleset required");
        var outPath = f.GetValueOrDefault("out") ?? rulesetPath;
        var cacheDir = f.GetValueOrDefault("cache-dir")
            ?? Path.Combine(Path.GetDirectoryName(Path.GetFullPath(rulesetPath))!, ".synopsis-cache");
        var force = args.Any(a => string.Equals(a, "--force", StringComparison.Ordinal));
        var endpoint = f.GetValueOrDefault("endpoint")
            ?? Environment.GetEnvironmentVariable("AZURE_OPENAI_ENDPOINT");
        var deployment = f.GetValueOrDefault("deployment")
            ?? Environment.GetEnvironmentVariable("AZURE_OPENAI_MINI_DEPLOYMENT")
            ?? "gpt-4o-mini";

        if (string.IsNullOrWhiteSpace(endpoint))
        {
            Console.Error.WriteLine(
                "AZURE_OPENAI_ENDPOINT not set (or pass --endpoint). " +
                "See samples/.env.synopsis.example.");
            return 64;
        }

        var ruleset = RuleSetIO.Load(rulesetPath);
        Console.WriteLine($"Loaded {ruleset.Rules.Count} rules from {rulesetPath}");
        Console.WriteLine($"Cache:    {cacheDir}");
        Console.WriteLine($"Endpoint: {endpoint}");
        Console.WriteLine($"Model:    {deployment}");

        IChatClient chat = BuildChatClient(endpoint!, deployment);
        var service = new SynopsisService(chat, cacheDir);

        var updated = new List<Rule>(ruleset.Rules.Count);
        var hits = 0;
        var generated = 0;
        var skipped = 0;
        var failed = 0;

        foreach (var rule in ruleset.Rules)
        {
            var hasSynopsis = rule.Metadata.TryGetValue("synopsis", out var existing)
                && !string.IsNullOrWhiteSpace(existing);
            if (hasSynopsis && !force)
            {
                skipped++;
                updated.Add(rule);
                continue;
            }

            try
            {
                var synopsis = await service.SynopsizeAsync(rule).ConfigureAwait(false);
                if (string.Equals(existing, synopsis, StringComparison.Ordinal))
                    hits++;
                else
                    generated++;

                var newMeta = new Dictionary<string, string>(rule.Metadata, StringComparer.Ordinal)
                {
                    ["synopsis"] = synopsis,
                };
                updated.Add(rule with { Metadata = newMeta });
                Console.WriteLine($"  ✓ {rule.Id,-32} {synopsis}");
            }
            catch (Exception ex)
            {
                failed++;
                Console.Error.WriteLine($"  ✗ {rule.Id}: {ex.Message}");
                updated.Add(rule);
            }
        }

        // Stable canonical order: keep the rule order from the input ruleset.
        var newRuleSet = ruleset with { Rules = updated };
        RuleSetIO.Save(newRuleSet, outPath);

        Console.WriteLine();
        Console.WriteLine(
            $"Done. generated={generated}  cached={hits}  skipped(existing)={skipped}  failed={failed}");
        Console.WriteLine($"Wrote: {outPath}");
        return failed == 0 ? 0 : 1;
    }

    private static IChatClient BuildChatClient(string endpoint, string deployment)
    {
        var azure = new AzureOpenAIClient(new Uri(endpoint), new DefaultAzureCredential());
        return azure.GetChatClient(deployment).AsIChatClient();
    }

    private static Dictionary<string, string> ParseFlags(string[] args)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        for (var i = 0; i < args.Length; i++)
        {
            if (args[i].StartsWith("--", StringComparison.Ordinal) && i + 1 < args.Length
                && !args[i + 1].StartsWith("--", StringComparison.Ordinal))
            {
                map[args[i][2..]] = args[i + 1];
                i++;
            }
        }
        return map;
    }
}
