<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LambdaRag.Core\LambdaRag.Core.csproj" />
    <PackageReference Include="UglyToad.PdfPig" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
