<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LambdaRag.Core\LambdaRag.Core.csproj" />
    <ProjectReference Include="..\LambdaRag.Persistence\LambdaRag.Persistence.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Azure.Search.Documents" />
  </ItemGroup>
</Project>